export const REVEAL_CORRECT_ANSWER_HIGHLIGHT_DURATION = 1500;
export const REVEAL_CORRECT_ANSWER_DURATION = 1000;
export const WRONG_ANSWER_SOUND_DURATION = 3000;
export const CORRECT_ANSWER_SOUND_DURATION = 4000;
export const TIME_OVER_DURATION_IN_SECONDS = 33;
export const FIRST_QUESTION_ORDER = 1;
