export const REVEAL_CORRECT_ANSWER_HIGHLIGHT_DURATION = 1500;
export const REVEAL_CORRECT_ANSWER_DURATION = 1000;
export const WRONG_ANSWER_SOUND_DURATION = 3000;
export const CORRECT_ANSWER_SOUND_DURATION = 4000;
